### ISSUE TITLE
Edge - Endpoints are not displayed in "browse"

### ISSUE THREAD

**Issue by mbouchenoire** [hopfront/hopfront#113]

**Comment by AnthonyMde** [comment]
The bug seems to be specific to Edge (7-8% of the market). 
As a workaround Tu-Uyen will be using Chrome for demos. 

Info: Specification is imported correctly, dashboard as well, problem does not seem to be related to docker but to Browse specific code.

I suggest to de-prioritize this ticket for now.

**Comment by AnthonyMde** [comment]
I'm not reproducing with Edge on MacOS though

**Comment by AnthonyMde** [comment]
Eventually it was just a local problem, with local storage.
