### ISSUE TITLE
Use OpenAPI specification in priority to determine and configure an API authentication

### ISSUE THREAD

**Issue by AnthonyMde** [hopfront/hopfront#149]
1 - Use OpenAPI specification to configure API authentication if it's specified.
2 - Allow user to add extra authentication configurations in parallel of the specification.

**Comment by mbouchenoire** [comment]
@remihrt @FabienWitick @AnthonyMde 

I've simply removed the possibility to configure static auth (basic auth / api key) outside of the spec because the previous system did not work like OpenAPI: we could only declare a "global" static authentication, while OpenAPI specifies the authentication at the operation level. I did this to avoid unnecessary work: we don't even know if users would need / want to configure a static auth outside of the spec. Nobody is blocked since the best practice is to declare a static auth at the spec level anyway.

**Comment by AnthonyMde** [comment]
Is it complicated to add it in parallel? 

Because even if having it in OpenAPi specification is the best practice we agreed that one of our priorities is to smooth the user experience, especially with specification configuration.

Moreover, we use several API's for testing which need API key but do not specify it in their specs. It can be tedious to modify each spec during the import to be able to play with it.

**Comment by mbouchenoire** [comment]
Yes it's complicated, because we need to manage the relationships between security schemes and individual operations in the UI. I agree that we need a smooth onboarding, but this has never been an issue yet.

**Comment by remihrt** [comment]
We could add some guide in Settings > Authentication that will explain how to setup authentication in the specification.
