### ISSUE TITLE
Bearer token authentication doesn't work

### ISSUE THREAD

**Issue by miquelferrerllompart** [hopfront/hopfront#185]
We have a couple of APIs that use the Bearer token strategy, but we are unable to make any authenticated calls.

Here is the local storage after successfully logging in.
![Screenshot 2024-02-14 at 12 45 12](https://github.com/hopfront/hopfront/assets/7172373/25d93a35-c579-4f19-bedd-af239b60859d)

When attempting a GET request, we encounter an error.
![Screenshot 2024-02-14 at 12 45 26](https://github.com/hopfront/hopfront/assets/7172373/d9122f16-e95d-4b6e-bab8-9d3173babf5d)

On the API call you could see that the token is not attached to the `Authorization` header the token.
![Screenshot 2024-02-14 at 12 48 20](https://github.com/hopfront/hopfront/assets/7172373/0850b30c-7bf7-4cb4-905f-d44a702223dd)

**Comment by mbouchenoire** [comment]
Hello!

In order to better understand your issue: are you using the "Global Authentication" set to "Access Token"? Or the `bearer` scheme of the `http` authentication specified _within your OpenAPI specification_?

Thank your for your time, we'll fix this issue asap :).

**Comment by mbouchenoire** [comment]
It looks like we identified the issue on our end (tell me if I'm wrong): It seems that your OpenAPI specification declares a `bearer` auth, but since the bearer token should be fetched via another endpoint, you declared a "Global Authentication" of type "Access Token" within HopFront to fetch this token. The issue is that currently, HopFront does not acknowledge any relationship between the `bearer` in your spec and the Global Authentication in HopFront. Feel free to tell us if this diagnostic is wrong!

We will implement a way for you to do that in the upcoming days, and I'll ping you when the release has been made :).

Thank you for your feedback!

**Comment by miquelferrerllompart** [comment]
That's it! Thanks, @mbouchenoire, for your prompt response.
Typically, we define our authentication endpoint at `/login`.
<img width="1459" alt="Screenshot 2024-02-14 at 20 26 47" src="https://github.com/hopfront/hopfront/assets/7172373/6d60603d-2a9c-4530-8c85-138816329d64">

Is there another way to handle it? We thought this was the standard approach.

**Comment by mbouchenoire** [comment]
> Is there another way to handle it? We thought this was the standard approach.

If you're talking about specifying how authentication works in your OpenAPI spec, this is indeed the standard approach. The issue with OpenAPI (currently) is that you cannot specify how the user should retrieve the token (`/login` endpoint in your case). This is why HopFront allows you to specify a "Global Authentication" of type "Access Token", which is a "better" way to define how to define your authentication via the `bearer` method (since you can specify the endpoint).

Thanks to the issue you created (this one), we found a bug / lack of a feature: the "Global Authentication" is not linked to the `bearer` specified in the spec. This is what we're currently working on :).

**Comment by mbouchenoire** [comment]
@miquelferrerllompart `v0.8.1` was just released. This release include a way for you to bind your `bearer` auth declared in your spec to an endpoint. This should allow you to use your authenticated endpoints with HopFront :). Feel free to tell us (here) if anything is wrong or does not work as expected!

**Comment by miquelferrerllompart** [comment]
Thank you! I've already tried it, and it works. 🎉
This tool is awesome with great potential.
Congratulations guys!
